---
name: Build STABLE stream container images
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  schedule:
    - cron: "50 5 * * 0" # 5:50 UTC sunday
  workflow_dispatch:

jobs:
  build_push_latest:
    name: Build and push latest image
    uses: ./.github/workflows/base_build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    with:
      stream_name: stable

