---
name: Build LATEST stream container images
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build_push_latest:
    name: Build and push latest image
    uses: ./.github/workflows/base_build.yml
    secrets: inherit
    with:
      stream_name: latest

